# Generated by Django 2.2.1 on 2019-09-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=32, verbose_name='文章名'),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=32, verbose_name='作者名'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(verbose_name='类型描述'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, verbose_name='文章类型'),
        ),
    ]
