# Generated by Django 2.2.1 on 2019-09-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190917_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='images/05.jpg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default='2019-09-14', verbose_name='日期'),
        ),
    ]
